/* ---------------------------------------------------------- */
/*                  Array global de productos                */
/* ---------------------------------------------------------- */
var productos = [
    { nombre: 'Resident Evil 4: Remake', precio: 12958, stock: 4, desarrollador: 'Capcom', categoria: 'Accion', edadDesde: '1' , edadHasta: '18', descripcionCorta: 'videojuego de acción-aventura', descripcionLarga: 'videojuego de acción-aventura de disparos en tercera persona perteneciente al subgénero de terror y supervivencia', envio: false, foto: 'https://image.api.playstation.com/vulcan/ap/rnd/202210/0706/EVWyZD63pahuh95eKloFaJuC.png' },
    { nombre: 'Dark Souls 3', precio: 12399, stock: 37, desarrollador: 'FromSoftware', categoria: 'Souls like', edadDesde: '1' , edadHasta: '18', descripcionCorta:'videojueo de rol de accion', descripcionLarga: 'videojuego de rol de acción, es la tercera entrega en la saga Souls', envio: true, foto: 'https://image.api.playstation.com/cdn/UP0700/CUSA03388_00/v8JlD8KcQUtTqaLBmpFnj1ESRR5zMkLk.png' },
    { nombre: 'World of Warcraft', precio: 4000, stock: 99, desarrollador: 'Blizzard', categoria: 'MMORPG', edadDesde: '1' , edadHasta: '18', descripcionCorta: 'videojuego de rol multijugador masivo en línea', descripcionLarga: 'videojuego de rol multijugador masivo en línea, es el cuarto juego lanzado establecido en el universo fantástico de Warcraft', envio: true, foto: 'https://media.vandal.net/m/7627/world-of-warcraft-wrath-of-the-lich-king-201421093351_1.jpg' },
    { nombre: 'Fallout 2', precio: 1699, stock: 23, desarrollador: 'Philips', categoria: 'CRPG', edadDesde: '1' , edadHasta: '18', descripcionCorta:'videojuego de rol post-apocalíptico', descripcionLarga: 'videojuego de rol post-apocalíptico desarrollado por Black Isle Studios', envio: false, foto: 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c3/PC_Game_Fallout_2.jpg/220px-PC_Game_Fallout_2.jpg' },
    { nombre: 'Dark Souls: Remastered', precio: 8299, stock: 23, desarrollador: 'FromSoftware', categoria: 'Souls Like', edadDesde: '1' , edadHasta: '18',descripcionCorta: 'videojuego de rol', descripcionLarga:'tienen lugar en un entorno de fantasía medieval oscura, donde el personaje del jugador lucha contra caballeros, dragones, fantasmas, demonios.', envio: true, foto: 'https://image.api.playstation.com/cdn/UP0700/CUSA08692_00/JxilRmpXkS3CCXUnr0gZTBOlqso3plaw.png' },
    { nombre: 'Devil may cry 3', precio: 66666, stock: 33, desarrollador: 'Capcom', categoria: 'Hack and Slash', edadDesde: '1' , edadHasta: '18',descripcionCorta: 'videojuego Hack and Slash', descripcionLarga:'es un videojuego de acción hack and slash desarrollado y publicado por Capcom para PlayStation 2 y luego adaptado a PC. Es la tercera entrega de la serie Devil May Cry, pero funciona como precuela de los dos primeros juegos', envio: true, foto: 'https://e.snmc.io/lk/lv/x/1fb77c258974535af0a53c61e757f7b7/5276839'} 
];
